-- WITHOUT USING JOIN
SELECT EMPLOYEES.FIRST_NAME, DEPARTMENTS.DEPARTMENT_NAME, EMPLOYEES.DEPARTMENT_ID
FROM EMPLOYEES, DEPARTMENTS
WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;
-- -----------------------



-- -----------------------
-- USING JOIN 
SELECT EMPLOYEES.FIRST_NAME, DEPARTMENTS.DEPARTMENT_NAME, EMPLOYEES.DEPARTMENT_ID
FROM EMPLOYEES 
    JOIN DEPARTMENTS ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID;


   -- OR

SELECT EMPLOYEES.FIRST_NAME, DEPARTMENTS.DEPARTMENT_NAME, EMPLOYEES.DEPARTMENT_ID
FROM EMPLOYEES JOIN DEPARTMENTS USING(DEPARTMENT_ID);
-- -----------------------


-- JOIN TYPES
SELECT *
FROM EMPLOYEES 
LEFT JOIN DEPARTMENTS USING(DEPARTMENT_ID);

SELECT *
FROM EMPLOYEES 
RIGHT JOIN DEPARTMENTS USING(DEPARTMENT_ID);

SELECT *
FROM EMPLOYEES 
CROSS JOIN DEPARTMENTS USING(DEPARTMENT_ID);
-- -----------------------------------------


-- self join
SELECT mgr.first_name as Manager, emp.first_name as Employee
FROM EMPLOYEES as mgr
	JOIN EMPLOYEES as emp
	ON mgr.manager_id = emp.employee_id;

-- --------------------


-- FIND NULL DEPTS
SELECT DEPARTMENTS.DEPARTMENT_NAME
FROM DEPARTMENTS
	LEFT JOIN EMPLOYEES
		ON DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID
WHERE EMPLOYEES.DEPARTMENT_ID IS NULL;

-- more
select 
	employees.first_name,
    employees.salary,
    (select avg(salary) from employees where department_id = employees.department_id) - employees.salary as "Avarage Department Salary" 
from employees
	join departments
		on employees.department_id = departments.department_id


-- --------------
SELECT DEPARTMENT_NAME
FROM EMPLOYEES
	JOIN DEPARTMENTS
		ON EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID
GROUP BY DEPARTMENT_NAME
HAVING MIN(SALARY) > 5000