-- Entity Relationship Diagram
------------------------------
-- -- Relations --
-- 1. one to one
-- 2. one to many
-- 3. many to many

-- ######################## --
-- ERD type Atributes
-- 1. Composite
-- 2. Multivalued
-- 3. Derived